import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="sticky top-0 z-10 border-b border-solid border-black/[.08] bg-white/80 backdrop-blur dark:border-white/[.145] dark:bg-black/80">
          <nav className="mx-auto flex w-full max-w-3xl items-center gap-6 px-6 py-4 sm:px-16">
            <Link
              href="/"
              className="text-base font-semibold text-black dark:text-zinc-50"
            >
              My App
            </Link>
            <div className="flex items-center gap-6 text-sm font-medium">
              <Link
                href="/about"
                className="text-zinc-600 transition-colors hover:text-black dark:text-zinc-400 dark:hover:text-zinc-50"
              >
                关于
              </Link>
              <Link
                href="/blog"
                className="text-zinc-600 transition-colors hover:text-black dark:text-zinc-400 dark:hover:text-zinc-50"
              >
                博客
              </Link>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
